services:
  - type: web
    name: esg-sdg-api
    env: python
    repo: https://github.com/unas0706/wbg
    branch: main
    pythonVersion: "3.10.11"
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --workers 2
    plan: starter
