services:
  - type: web
    name: esg-sdg-api
    env: python
    repo: https://github.com/unas0706/wbg
    branch: main
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app -b 0.0.0.0:$PORT --workers 2 --timeout 120
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
